// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "xl9535_relay.h"
#include "ui_input_helpers.h"  // ← Add this
#include <stdlib.h>

// Global variables
int vreme_rada_motor1 = 0;
int vreme_rada_motor2 = 0;
int vreme_pauze = 0;
int zeljena_temp_radionice = 0;
int max_temp_kotla = 0;

//fleg-ovi za releje
bool fleg_dodavac_1 = false;
bool fleg_dodavac_2 = false;
bool fleg_dimnjak = false;
bool fleg_glavni_ventilator = false;

void Total_stop_function(lv_event_t * e)
{
	// Your code here
}
void Vreme_rada_m1(lv_event_t * e) {
    process_input(ui_TextArea3, ui_Label18, &vreme_rada_motor1);
}

void Vreme_rada_m2(lv_event_t * e) {
    process_input(ui_TextArea3, ui_Label19, &vreme_rada_motor2);
}

void Vreme_pauze(lv_event_t * e) {
    process_input(ui_TextArea3, ui_Label24, &vreme_pauze);
}

void Zeljena_temp_radionice(lv_event_t * e) {
    process_input(ui_TextArea1, ui_Label7, &zeljena_temp_radionice);
}

void Maks_temp_kotla(lv_event_t * e) {
    process_input(ui_TextArea1, ui_Label8, &max_temp_kotla);
}

void Datum_izmena(lv_event_t * e)
{
	// Your code here
}

void Vreme_izmena(lv_event_t * e)
{
	// Your code here
}

void prekidac_dimnjak(lv_event_t * e)
{
	fleg_dimnjak = true;
	Serial.println(fleg_dimnjak);
}

void prekidac_dodavac_1(lv_event_t * e)
{
	Serial.println("uspeo si");
  //relayBoard.relayOn(5);
}

void prekidac_dodavac_2(lv_event_t * e)
{
	
  //relayBoard.relayOn(5);
}

void prekidac_glavni_ventilator(lv_event_t * e)
{
	// Your code here
}


