// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void prekidac_dodavac_1(lv_event_t * e);
void prekidac_dodavac_2(lv_event_t * e);
void prekidac_dimnjak(lv_event_t * e);
void prekidac_glavni_ventilator(lv_event_t * e);
void Total_stop_function(lv_event_t * e);
void Vreme_rada_m1(lv_event_t * e);
void Vreme_rada_m2(lv_event_t * e);
void Vreme_pauze(lv_event_t * e);
void Zeljena_temp_radionice(lv_event_t * e);
void Maks_temp_kotla(lv_event_t * e);
void Datum_izmena(lv_event_t * e);
void Vreme_izmena(lv_event_t * e);

// Global variables
extern int vreme_rada_motor1 ;
extern int vreme_rada_motor2 ;
extern int vreme_pauze ;
extern int zeljena_temp_radionice ;
extern int max_temp_kotla ;

//fleg-ovi za releje
extern bool fleg_dodavac_1 ;
extern bool fleg_dodavac_2 ;
extern bool fleg_dimnjak ;
extern bool fleg_glavni_ventilator ;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
