// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MANUELNI_RAD_H
#define UI_MANUELNI_RAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_manuelni_rad
extern void ui_manuelni_rad_screen_init(void);
extern void ui_manuelni_rad_screen_destroy(void);
extern lv_obj_t * ui_manuelni_rad;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label10;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label12;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label15;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button6;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

