// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MENI_H
#define UI_MENI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_meni
extern void ui_meni_screen_init(void);
extern void ui_meni_screen_destroy(void);
extern lv_obj_t * ui_meni;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container4;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Colorwheel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

