// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_REZIMI_RADA_H
#define UI_REZIMI_RADA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_rezimi_rada
extern void ui_rezimi_rada_screen_init(void);
extern void ui_rezimi_rada_screen_destroy(void);
extern void ui_event_rezimi_rada(lv_event_t * e);
extern lv_obj_t * ui_rezimi_rada;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

